project:
  type: website

website:

  navbar:

    logo: images/logo.png

    left:

      - text: Home
        href: index.qmd

      - text: Story
        href: "#introduction"

      - text: NASA Orrery
        href: https://eyes.nasa.gov/apps/orrery/#/home

      - text: GitHub
        href: https://github.com/joeltang1110/calculus-neptune

format:
  html:
    theme: cyborg
    toc: true
    number-sections: true
    css: styles.css

    